name: MCONE-CitybuildSystem
authors: [Marvin Hülsmann]
version: ${project.version}
api-version: '1.13'
main: eu.mcone.citybuild.Citybuild
description: Ein CityBuild Plugin von MCONE

depend: [MCONE-BukkitCoreSystem, PlotSquared]

permissions:
  citybuild:
    description: Citybuild root permission
    children:
      citybuild.rand:
        description: Allows to change the border of all plots